### ISSUE TITLE
Offset/Amount is not working 

### ISSUE THREAD

**Issue by RichKarona** [ArjenLammers/oqlmodule#10]
Hi,

Good work on the module which is very useful.

But - the offset/amount does not work, 
changing the offset seems to have no effect and the same rows are returned.
looks (to me) as if OQL.java line 78 needs correcting?

**Comment by ghost** [comment]
That should not even be a question ;-)
schema.setAmount(amount != null ? **offset** : 0);
For us this was a breaking bug...
(set aside the Mendix bug of combining offset/amount with IRetrievalSchema and union queries)

**Comment by ArjenLammers** [comment]
This was fixed in the project.
Please let me know if it doesn't work for some reason.
