### ISSUE TITLE
Mendix Studio Pro 8.15.2, After imported the OQL 2.4 package, it always throw 9 errors.

### ISSUE THREAD

**Issue by ShawnXiao-NEX** [ArjenLammers/oqlmodule#13]
Once imported into my project, it throws 9 errors: the selected Java action "CommunityCommons.StringFromFile" no longer exists, etc...

Mendix Studio Pro 8.15.2
OQL 2.4 package

![OQL](https://user-images.githubusercontent.com/64119104/99935013-a1575200-2d9a-11eb-8937-6221b51d61e0.png)

**Comment by ArjenLammers** [comment]
Hi, import the CommunityCommons library and adapt the layouts to your projects structure to fix this.
