### ISSUE TITLE
Upgrade to 8.12 to prepare for upgrade to 9.05 

### ISSUE THREAD

**Issue by kmn0** [ArjenLammers/oqlmodule#15]
We are using this module and are preparing for an upgrade to Studio 9.05. For this upgrade the module needs to be at least on 8.12. Is there a timeline when this module will be upgraded?
Best regards,
Gerrit van Kammen

**Comment by TimvanSteenbergen** [comment]
Same here. Tried it and ran into errors that I can not solve myself. Need this OQL-module for some awesome stuff.

**Comment by ArjenLammers** [comment]
Wasn't specific to 9.
Compilation error due to missing OpenCSV library.
2.6 released to compensate this.

Please be more detailed if otherwise.
