### ISSUE TITLE
Wrong objects retrieved

### ISSUE THREAD

**Issue by TimvanSteenbergen** [ArjenLammers/oqlmodule#16]
`FROM MyModule.MyEntity M
WHERE ((M.attrib1='_031')
and (M.attrib2 ='Payment')
and  (M.Date is null)
and (M.OtherDate is not null))
SELECT count(*)`

On production this results in 44000

Now retrieving the list with attrib1, attrib2 and Date:
`FROM MyModule.MyEntity M
WHERE ((M.attrib1='_031')
and (M.attrib2 ='Payment')
and  (M.Date is null)
and (M.OtherDate is not null))
SELECT M.attrib1, M.attrib2, M.Date`
This contains several duplicate entities instead of only unique correct entities. MyEntity.attrib1 is unique and so enforced via the entity's validation.

This only happens on production, where the MyModule.MyEntity is read and written constantly. Same query on the same database-content in any other environment works fine. The likely reason is the inactivity on those environments.

Another pointer to solve this, is that adding DISTINCT to the attrib1: `SELECT DISTINCT(M.attrib1), M.attrib2, M.Date` makes the result come out correctly.

**Comment by TimvanSteenbergen** [comment]
This only happens on production, where the MyThing-entity is used and read- and written constantly. Same query on the same database-content in any other environment works fine.

**Comment by ArjenLammers** [comment]
Hi Tim,

I'm not doing any support on the working of OQL itself, that has to be addressed through Mendix platform support.
The module is only a means to translate results to domain model entities.

Kind regards,
Arjen Lammers
