### ISSUE TITLE
Error exporting large table to CSV

### ISSUE THREAD

**Issue by jeroen-huizer-conclusion** [ArjenLammers/oqlmodule#17]
Hi Arjen,

I use the OQL module to create CSV-exports of a few large tables in our application to offload the tables to a datawarehouse.
So far, the OQL module is the only module that I found that is capable of exporting these large tables, without running into OOM issues, and it is also very fast, so great job on that!

However, I do run into an issue when using this in the Mendix Cloud. At some point the export runs into a Disk Quota exceeded error; see tip of the stacktrace below. Which is odd, because the file should be well within limits for the disk (3 Gb vs 160 Gb).
Mendix support gave some vague answer about 'internal storage' vs. 'file storage'.

Do you have any idea what could cause this and how I can avoid / work around it?

Thanks!
Jeroen Huizer

Caused by: java.io.IOException: Disk quota exceeded
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(Unknown Source)
	at java.base/java.io.File.createTempFile(Unknown Source)
	at oql.actions.ExportOQLToCSV.executeAction(ExportOQLToCSV.java:73)
	at oql.actions.ExportOQLToCSV.executeAction(ExportOQLToCSV.java:38)

Edit: fix typo

**Comment by ArjenLammers** [comment]
Hi Jeroen,

Your Mendix application runs inside a container which has limited storage (probably the 3GB limit). Your project also resides in there and some other things. The output of your statement gets buffered there first.
You can try the ZIP functionality to work around this limitation.
A 1GB zipped text file should already be a huge amount of data.

Kind regards,
Arjen Lammers

**Comment by jeroen-huizer-conclusion** [comment]
Hi Arjen,

Thanks for the reply, that clarifies things a lot.

Zipping is not an option, unfortunately, because the ETL tool of the datawarehouse cannot easily process ZIP files.
As a workaround I limit the export to about 1M records and write multiple files per table, that works great.

Do you know if there is any way to avoid writing to the container storage and write directly to the file storage?

In any case, you can consider this issue solved.

Regards,
Jeroen

**Comment by ArjenLammers** [comment]
hi @jeroen-huizer-conclusion ,
I intentionally leveraged the container storage to avoid implications on the underlying file storage engine (e.g. S3/Azure Blob Storage) combined with long running operations (like complex paginated queries).
the ZIP option was introduced to overcome the size limitation somewhat (3GB of compressed data is a lot of plain text).

I would suggest one of the following approaches:
- Look for another place to do the unzip; this will depend on your environment.
- Make multiple exports and merge the files using the Core.storageFileDocument directly (I'm not aware of such public available action).

kind regards,
Arjen
