### ISSUE TITLE
ExportOQLToCSV does not apply entity level security

### ISSUE THREAD

**Issue by mkumpf** [ArjenLammers/oqlmodule#19]
Not sure if this is something I am doing wrong.  I have an app that uses the Multitenant module.  Entity security is controlled via entities in that module.  However, when I login as a tenant user and execute an OQL statement with this Java action, I see information for all Tenants, not just the Tenant I am a part of.

**Comment by ArjenLammers** [comment]
hi @mkumpf , this module leverages the OQL query functionality of the Mendix platform which doesn't take security in consideration (see https://docs.mendix.com/refguide/oql/).
