### ISSUE TITLE
Limit and offset must explicitly be set to 0

### ISSUE THREAD

**Issue by tieniber** [ArjenLammers/oqlmodule#2]
Sharing some [frustration from the forum](https://forum.mendixcloud.com/link/questions/90820)

It seems you need to set the limit and offset in the OQL action and cannot leave them empty. Allowing empty (the default) would be much more user friendly.

**Comment by ArjenLammers** [comment]
Will be fixed in the next versoin.
See https://github.com/ArjenLammers/oqlmodule/commit/d13eaa1809e025b17b61300409d29dd731cd8c50
