### ISSUE TITLE
German Umlauts are broken

### ISSUE THREAD

**Issue by TorstenKoe** [ArjenLammers/oqlmodule#22]
When exporting OQL to CSV with Microflow and downloading the CSV the german Umlauts (ä,ö,ü) are broken.
LÜBBECKE -> LÃœBBECKE

Seems that the codepage ist wrong ;-)

If i export the OQL to table everything is fine!

Thanks
Torsten

**Comment by ArjenLammers** [comment]
Hi Torsten,

The CSV is exported using UTF-8.
If you view or import your data using that character set, I expect the umlauts to appear correct.

Kind regards,
Arjen Lammers

**Comment by TorstenKoe** [comment]
Hi Arjen,
thanks, that makes it clear.
Automatic open in Excel is not the best thing for this..

Best regards
Torsten
